# - name: variables to print
#   hosts: web
#   tasks:
#   - name: print the information
#     ansible.builtin.debug:
#       msg: "Hello {{NAME}}, Good {{GREETING}}"


- name: Variables to print
  hosts: web
  tasks:
    - name: Print the information
      ansible.builtin.debug:
        msg: "Hello {{ NAME }}, Good {{ GREETING }}"


