- name: install packages
  host: web
  become: yes
  tasks: 
   name: install packages
   ansible.builtin.package:
     list : {{ item }}
     loop:
      - nginx
      - postgress
      - mysql
      
