- name: user add
  hosts: web
  become: yes
  tasks: 
   - name: check wheteher user exists or not
     ansible.builtin.command: id expense
     register: USER
     ignore_errors: TRUE

   - name: print user information
     ansible.builtin.debug:
       msg: "print user info {{ USER }}"

   - name: create user
     ansible.builtin.command: useradd expense
     ex: if USER.rc != 0  

     